import random

# Sample lists of first names and last names
first_names = [
    "Liam", "Emma", "Noah", "Olivia", "William", "Ava", "James", "Isabella",
    "Logan", "Sophia", "Benjamin", "Mia", "Mason", "Charlotte", "Elijah",
    "Amelia", "Oliver", "Evelyn", "Jacob", "Abigail", "Lucas", "Harper",
    "Michael", "Emily", "Alexander", "Ella", "Ethan", "Avery", "Daniel",
    "Sofia", "Matthew", "Camila", "Aiden", "Aria", "Henry", "Scarlett",
    "Joseph", "Victoria", "Jackson", "Madison", "Samuel", "Luna", "Sebastian",
    "Grace", "David", "Chloe", "Carter", "Penelope", "Wyatt", "Layla",
    "Jayden", "Riley", "John", "Zoey", "Owen", "Nora", "Dylan", "Lily",
    "Luke", "Eleanor", "Gabriel", "Hannah", "Anthony", "Lillian", "Isaac",
    "Addison", "Grayson", "Aubrey", "Jack", "Ellie", "Julian", "Stella",
    "Levi", "Natalie", "Christopher", "Zoe", "Joshua", "Leah", "Andrew",
    "Hazel", "Lincoln", "Violet", "Mateo", "Aurora", "Ryan", "Savannah",
    "Jaxon", "Audrey", "Nathan", "Brooklyn", "Aaron", "Bella", "Isaiah",
    "Claire", "Thomas", "Skylar", "Charles", "Lucy", "Caleb", "Paisley",
    "Josiah", "Everly", "Christian", "Anna", "Hunter", "Caroline", "Eli",
    "Nova", "Jonathan", "Genesis", "Connor", "Emilia", "Landon", "Kennedy",
    "Adrian", "Samantha", "Asher", "Maya", "Cameron", "Willow", "Leo",
    "Kinsley", "Theodore", "Naomi", "Jeremiah", "Aaliyah", "Hudson",
    "Elena", "Robert", "Sarah", "Easton", "Ariana", "Nolan", "Allison",
    "Nicholas", "Gabriella", "Ezra", "Alice", "Colton", "Madelyn", "Angel",
    "Cora", "Brayden", "Ruby", "Jordan", "Eva", "Dominic", "Serenity",
    "Austin", "Autumn", "Ian", "Adeline", "Adam", "Hailey", "Elias",
    "Gianna", "Jaxson", "Valentina", "Greyson", "Isla", "Jose", "Eliana",
    "Ezekiel", "Quinn", "Carson", "Nevaeh", "Evan", "Ivy", "Maverick",
    "Sadie", "Bryson", "Piper", "Jace", "Lydia", "Cooper", "Alexa", "Xavier",
    "Josephine", "Parker", "Emery", "Roman", "Julia", "Jason", "Delilah",
    "Santiago", "Arianna", "Chase", "Vivian", "Sawyer", "Kaylee", "Gavin",
    "Sophie", "Leonardo", "Brielle", "Kayden", "Madeline", "Ayden",
    "Peyton", "Jameson", "Rylee", "Bentley", "Clara", "Zachary", "Raelynn",
    "Everett", "Melanie", "Axel", "Mackenzie", "Tyler", "Autumn", "Micah",
    "Faith", "Vincent", "Molly", "Bryce", "Eloise", "Victor", "Cecilia",
    "Milo", "Mabel", "Patrick", "Ruth", "Abel", "Ariella", "Marcus",
    "Paige", "Max", "Gemma", "Harrison", "Jocelyn", "Waylon", "Angelina",
    "Weston", "Taylor", "Silas", "Arya", "Brantley", "Eden", "Braxton",
    "Aubree", "Ryker", "Emerson", "George", "Adalynn", "Zane", "Ryleigh",
    "Elliot", "Valeria", "Arthur", "Aspen", "Beau", "Juliette", "Dallas",
    "Kehlani", "Emmanuel", "Catalina", "Finn", "Leilani", "Graham",
    "Brooke", "Kaleb", "Lola", "River", "Adriana", "Jasper", "Gracie",
    "Jude", "Payton", "Blake", "Blakely", "Eric", "Alaina", "Myles",
    "Charlee", "Brody", "Miriam", "Paxton", "Giselle", "Jonah", "Brynn",
    "Peter", "Katherine", "Kane", "Felicity", "Maxwell", "Isabel", "Abraham",
    "Laila", "Jayce", "Harmony", "Ashton", "Georgia", "Kayleigh", "Journey",
    "Elliott", "Alayna", "August", "Jane", "Giovanni", "Juliana", "Brandon",
    "Tessa", "Rowan", "Lila", "Paxton", "Laura", "Dean", "Adaline", "Matias",
    "Summer", "Kyrie", "Sloane", "Andres", "Everleigh", "Kai", "Maddox",
    "Ryland", "Griffin", "Matteo", "Cody", "Roberto", "Tanner", "Theo",
    "Zander", "Emilio", "Karter", "Malcolm", "Abel", "Kane", "Troy",
    "Zayn", "Ezequiel", "Ari", "Conner", "Rafael", "Enzo", "Nico", "Israel",
    "Jett", "Mohamed", "Apollo", "Nasir", "Ronan", "Niko", "Phoenix",
    "Kason", "Brady", "Kamden", "Archer", "Rory", "Andy", "Landen",
    "Armando", "Derek", "Colson", "Drew", "Dawson", "Cesar", "Simon",
    "Joaquin", "Gage", "Marshall", "Jalen", "Santana", "Alvin", "Gunner",
    "Amari", "Mitchell", "Emerson", "Nehemiah", "Desmond", "Casey",
    "Jaylen", "Dillon", "Gregory", "Damon", "Jared", "Travis", "Johnny",
    "Eduardo", "Gustavo", "Donovan", "Dante", "Martin", "Dax", "Kenzo",
    "Zayden", "Kade", "Kingston", "Moses", "Crosby", "Dakota", "Drake",
    "Eden", "Esteban", "Ford", "Sincere", "Royal", "Ruben", "Ulises",
    "Wells", "Lucian", "Dorian", "Alec", "Ellis", "Ronnie", "Brock",
    "Payton", "Enoch", "Devin", "Flynn", "Cassius", "Eddie", "Frank",
    "Kristopher", "Lawson", "Nikolai", "Mohammad", "Ayaan", "Coen",
    "Colt", "Khalid", "Kobe", "Boone", "Wilson", "Brycen", "Reed", "Bronson",
    "Russell", "Shawn", "Jefferson", "Cason", "Kameron", "Alfred", "Dane",
    "Raul", "Jaziel", "Mekhi", "Conrad", "Hamza", "Alessandro", "Trey",
    "Ronin", "Rocco", "Brayan", "Houston", "Finnegan", "Jamari", "Kendrick",
    "Frederick", "Trenton", "Benson", "Jamir", "Jadiel", "Valentino",
    "Luka", "Azariah", "Dustin", "Baker", "Mohammad", "Stanley", "Uriah",
    "Tatum", "Kaysen", "Roland", "Ernesto", "Beckham", "Johan", "Clay",
    "Harry", "Raylan", "Kellen", "Lennox", "Mauricio", "Mohammed",
    "Otis", "Reece", "Spencer", "Sylas", "Tomas", "Tripp", "Bodhi",
    "Carmelo", "Cullen", "Darwin", "Dax", "Eason", "Isaiah", "Izaiah",
    "Jefferson", "Jensen", "Jonas", "Lance", "Leland", "Lennon", "Leon",
    "Leonidas", "Louis", "Madden", "Major", "Maximus", "Miller", "Otto",
    "Rafael", "Raiden", "Randy", "Remington", "Rey", "Richard", "Rowan",
    "Sage", "Santino", "Soren", "Sterling", "Thaddeus", "Thatcher",
    "Trace", "Tristen", "Zayne", "Axton", "Benicio", "Bodie", "Braiden",
    "Branson", "Cairo", "Callen", "Carmine", "Colten", "Dayton", "Dior",
    "Eliseo", "Ellison", "Elon", "Emmitt", "Garrison", "Guillermo",
    "Harlan", "Hezekiah", "Isaac", "Isaias", "Jase", "Jasper", "Jax",
    "Jay", "Jericho", "Jett", "Jimmy", "Jon", "Joziah", "Julius", "Justice",
    "Kaiden", "Kane", "Karson", "Keegan", "Kian", "Killian", "King",
    "Kingsley", "Knox", "Kole", "Krew", "Kylo", "Kyrie", "Langston",
    "Lawrence", "Layton", "Lian", "Lyle", "Lyric", "Magnus", "Makai",
    "Makhi", "Matteo", "Maxim", "Maxwell", "Memphis", "Mordechai",
    "Moses", "Nash", "Noe", "Orlando", "Quentin", "Quincy", "Ramon",
    "Remy", "Rhys", "Ridge", "Rocco", "Rodrigo", "Ronin", "Roy", "Ruben",
    "Samson", "Solomon", "Sonny", "Stetson", "Talon", "Tanner", "Terrence",
    "Titan", "Tobias", "Trenton", "Tru", "Ty", "Tyson", "Uriah", "Wade",
    "Warren", "Wilder", "Xander", "Zaid", "Zayne", "Zechariah"
]

last_names = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller",
    "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez",
    "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
    "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark",
    "Ramirez", "Lewis", "Robinson", "Walker", "Young", "Allen", "King",
    "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green",
    "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell",
    "Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz",
    "Parker", "Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris",
    "Morales", "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan",
    "Cooper", "Peterson", "Bailey", "Reed", "Kelly", "Howard", "Ramos",
    "Kim", "Cox", "Ward", "Richardson", "Watson", "Brooks", "Chavez",
    "Wood", "James", "Bennett", "Gray", "Mendoza", "Ruiz", "Hughes",
    "Price", "Alvarez", "Castillo", "Sanders", "Patel", "Myers", "Long",
    "Ross", "Foster", "Jimenez", "Powell", "Jenkins", "Perry", "Russell",
    "Sullivan", "Bell", "Coleman", "Butler", "Henderson", "Barnes",
    "Gonzales", "Fisher", "Vasquez", "Simmons", "Romero", "Jordan",
    "Patterson", "Alexander", "Hamilton", "Graham", "Reynolds", "Griffin",
    "Wallace", "Moreno", "West", "Cole", "Hayes", "Bryant", "Herrera",
    "Gibson", "Ellis", "Tran", "Medina", "Aguilar", "Stevens", "Murray",
    "Ford", "Castro", "Marshall", "Owens", "Harrison", "Fernandez",
    "McDonald", "Woods", "Washington", "Kennedy", "Wells", "Vargas",
    "Henry", "Chen", "Freeman", "Webb", "Tucker", "Guzman", "Burns",
    "Crawford", "Olson", "Simpson", "Porter", "Hunter", "Gordon", "Mendez",
    "Silva", "Shaw", "Snyder", "Mason", "Dixon", "Munoz", "Hunt", "Hicks",
    "Holmes", "Palmer", "Wagner", "Black", "Robertson", "Boyd", "Rose",
    "Stone", "Salazar", "Fox", "Warren", "Mills", "Meyer", "Rice",
    "Schmidt", "Garza", "Daniels", "Ferguson", "Nichols", "Stephens",
    "Soto", "Weaver", "Ryan", "Gardner", "Payne", "Grant", "Dunn",
    "Kelley", "Spencer", "Hawkins", "Arnold", "Pierce", "Vazquez",
    "Hansen", "Peters", "Santos", "Hart", "Bradley", "Knight", "Elliott",
    "Cunningham", "Duncan", "Armstrong", "Hudson", "Carroll", "Lane",
    "Riley", "Andrews", "Alvarado", "Ray", "Delgado", "Berry", "Perkins",
    "Hoffman", "Johnston", "Matthews", "Pena", "Richards", "Contreras",
    "Willis", "Carpenter", "Lawrence", "Sandoval", "Guerrero", "George",
    "Chapman", "Rios", "Estrada", "Ortega", "Watkins", "Greene", "Nunez",
    "Wheeler", "Valdez", "Harper", "Burke", "Larson", "Santiago",
    "Maldonado", "Morrison", "Franklin", "Carlson", "Austin", "Dominguez",
    "Carr", "Lawson", "Jacobs", "Obrien", "Lynch", "Singh", "Vega",
    "Bishop", "Montgomery", "Oliver", "Jensen", "Harvey", "Williamson",
    "Gilbert", "Dean", "Sims", "Espinoza", "Howell", "Li", "Wong",
    "Reid", "Hanson", "Le", "McCoy", "Garrett", "Burton", "Fuller",
    "Wang", "Weber", "Welch", "Rojas", "Lucas", "Marquez", "Fields",
    "Park", "Yang", "Little", "Banks", "Padilla", "Day", "Walsh",
    "Bowman", "Schultz", "Luna", "Fowler", "Mejia", "Davidson", "Acosta",
    "Brewer", "May", "Holland", "Juarez", "Newman", "Pearson", "Curtis",
    "Cortez", "Douglas", "Schneider", "Joseph", "Barrett", "Navarro",
    "Figueroa", "Keller", "Avila", "Wade", "Molina", "Stanley", "Hopkins",
    "Campos", "Barnett", "Bates", "Chambers", "Caldwell", "Beck",
    "Lambert", "Miranda", "Byrd", "Craig", "Ayala", "Lowe", "Frazier",
    "Powers", "Neal", "Leonard", "Gregory", "Carrillo", "Sutton", "Fleming",
    "Rhodes", "Shelton", "Schwartz", "Norris", "Jennings", "Watts",
    "Duran", "Walters", "Cohen", "McDaniel", "Moran", "Parks", "Steele",
    "Vaughn", "Becker", "Holt", "Deleon", "Barker", "Terry", "Hale",
    "Leon", "Benson", "Haynes", "Horton", "Miles", "Lyons", "Pham",
    "Graves", "Bush", "Thornton", "Wolfe", "Warner", "Cabrera", "McKinney",
    "Mann", "Zimmerman", "Dawson", "Lara", "Fletcher", "Page", "Mccarthy",
    "Love", "Robles", "Cervantes", "Solis", "Erickson", "Reeves", "Chang",
    "Klein", "Salinas", "Fuentes", "Baldwin", "Daniel", "Simon", "Velasquez",
    "Hardy", "Higgins", "Aguirre", "Lin", "Cummings", "Chandler", "Sharp",
    "Barber", "Bowen", "Ochoa", "Dennis", "Robbins", "Liu", "Ramsey",
    "Francis", "Griffith", "Paul", "Blair", "Oconnor", "Cardenas", "Pacheco",
    "Cross", "Calderon", "Quinn", "Moss", "Swanson", "Chan", "Rivas",
    "Khan", "Rodgers", "Serrano", "Fitzgerald", "Rosales", "Stevenson",
    "Christensen", "Manning", "Gill", "Curry", "McKee", "Frost", "Petersen",
    "Briggs", "David", "Chavez", "Maldonado", "Brock", "Gibson", "Stokes",
    "Kramer", "Munoz", "Robbins", "Chambers", "Lindsey", "Higgins", "Day",
    "Stevens", "Griffith", "Erickson", "Sanders", "Wade", "McDonald",
    "Jensen", "Wood", "Morgan", "Gibson", "Chavez", "Hawkins", "Bush",
    "Hughes", "Lowe", "Ramos", "Schmidt", "Alexander", "Holmes", "Meyer",
    "Matthews", "Perry", "Patterson", "Kelley", "Lawson", "Williamson",
    "Reynolds", "Oliver", "Kim", "Norris", "Vasquez", "Hunter", "Pearson",
    "Mills", "Gardner", "Bishop", "Mendoza", "Morales", "Parker", "Kim",
    "Wallace", "Lamb", "Bates", "Floyd", "Riley", "Hart", "Murray", "Jones",
    "Gilbert", "Hoffman", "Warren", "Reid", "Crawford", "Carpenter",
    "Frazier", "Sanders", "Adams", "Harris", "Butler", "Wells", "Barrett",
    "Foster", "Dixon", "Reynolds", "Armstrong", "Lopez", "Dawson", "Brooks",
    "Hicks", "Burke", "Barker", "Steele", "Henderson", "Montgomery", "Lloyd",
    "Barnes", "Bryant", "Torres", "Wagner", "Harrison", "Evans", "Phillips",
    "Hughes", "Ellis", "Carter", "Jones", "Bailey", "Howard", "Miller",
    "Sullivan", "Bell", "Collins", "Richardson", "Gomez", "Stevens", "Lawson",
    "Holland", "Cook", "Bennett", "Murphy", "Flores", "Long", "Patterson",
    "Perry", "Cruz", "Hayes", "Gutierrez", "Ford", "Ross", "Powell", "Hughes",
    "Fisher", "Fowler", "Duncan", "Black", "Johnson", "White", "Morris",
    "Jackson", "Diaz", "Lopez", "Martin", "Clark", "Allen", "King", "Wright",
    "Young", "Green", "Hill", "Scott", "Walker", "Garcia", "Lewis", "Rodriguez",
    "Robinson", "Campbell", "Mitchell", "Carter", "Roberts", "Gomez",
    "Phillips", "Evans", "Turner", "Diaz", "Parker", "Collins", "Edwards",
    "Stewart", "Sanchez", "Morris", "Rogers", "Reed", "Cook", "Morgan",
    "Bell", "Murphy", "Bailey", "Rivera", "Cooper", "Richardson", "Cox",
    "Howard", "Ward", "Torres", "Peterson", "Gray", "Ramirez", "James",
    "Watson", "Brooks", "Kelly", "Sanders", "Price", "Bennett", "Wood",
    "Barnes", "Ross", "Henderson", "Coleman", "Jenkins", "Perry", "Powell",
    "Long", "Patterson", "Hughes", "Flores", "Washington", "Butler",
    "Simmons", "Foster", "Gonzales", "Bryant", "Alexander", "Russell",
    "Griffin", "Diaz", "Hayes"
]


def get_random_person_name(**kwargs):
    first_name = random.choice(first_names)
    middle_initial = " " + chr(random.randint(65, 90)) + '.' if random.random() < 1 / 4 else ''
    last_name = random.choice(last_names)

    if random.random() < 1 / 8:
        last_name += ' ' + random.choice(last_names)

    if random.random() < 1 / 8:
        first_name += ' ' + random.choice(first_names)

    name = f"{first_name}{middle_initial} {last_name}".strip()

    return name if random.random() < 1 / 8 else name.upper()
